# General settings
baseURL = "https://alexanderstephan.xyz/"
languageCode = "en-us"
title = "hi, i'm Alex"
summaryLength = 50

# Parameters
[params]

subtitle = "Social links here"
dateFmt = "02.01.2006"
author = "Alexander Stephan"
contact = "a [dot] stephan [at] mailbox [dot] org"
showDate = true
math = true

# Enter your social media links her
[params.social.share]
github = true
github_link = "https://github.com/alexanderstephan"
flickr = true
flickr_link = "https://www.flickr.com/photos/155232150@N04"
mixcloud = true
mixcloud_link = "https://www.mixcloud.com/alexander_stephan/"

# Header
[menu]

[[menu.main]]
identifier = "gallery"
name = "gallery"
url = "/gallery/"
weight = 2

[[menu.main]]
identifier = "imprint"
name = "projects"
url = "/projects/"
weight = 2

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'native'
tabWidth = 4

[security]
enableInlineShortcodes = false

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[security.funcs]
getenv = ['^HUGO_']

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true

